### ISSUE TITLE
Inconsistent use of semicolons 

### ISSUE THREAD

**Issue by zapacni** [brokenVectors/brokenBot#4]
In some lines there are semicolons after statements but some there aren't. This can be observed in main.js and possibly other files but im too lazy to check but yea

**Comment by brokenVectors** [comment]
Thanks for letting us know. We agree there is an issue and we're looking into it.

**Comment by brokenVectors** [comment]
fixered it thanks

**Comment by brokenVectors** [comment]
(https://github.com/brokenVectors/brokenBot/commit/b41e959e0a70bc6bab9cf319bd730cd6ee1ce991)
